### ISSUE TITLE
Invalid URI for NameNode address (check fs.defaultFS): lustrefs:/// has no authority

### ISSUE THREAD

**Issue by b-long** [Seagate/lustrefs#2]
Fairly certain I'm using this properly, but when I run `service hadoop-hdfs-namenode restart`, I get the following output in `/var/log/hadoop-hdfs/hadoop-hdfs-namenode-lustre3.log` :

```
************************************************************/
2015-10-25 11:29:53,262 INFO  namenode.NameNode - registered UNIX signal handlers for [TERM, HUP, INT]
2015-10-25 11:29:53,266 INFO  namenode.NameNode - createNameNode []
2015-10-25 11:29:54,162 INFO  impl.MetricsConfig - loaded properties from hadoop-metrics2.properties
2015-10-25 11:29:54,417 INFO  impl.MetricsSystemImpl - Scheduled snapshot period at 10 second(s).
2015-10-25 11:29:54,417 INFO  impl.MetricsSystemImpl - NameNode metrics system started
2015-10-25 11:29:54,426 INFO  namenode.NameNode - fs.defaultFS is lustrefs:///
2015-10-25 11:29:55,188 FATAL namenode.NameNode - Failed to start namenode.
java.lang.IllegalArgumentException: Invalid URI for NameNode address (check fs.defaultFS): lustrefs:/// has no authority.
        at org.apache.hadoop.hdfs.server.namenode.NameNode.getAddress(NameNode.java:423)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.getAddress(NameNode.java:413)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.getRpcServerAddress(NameNode.java:464)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.loginAsNameNodeUser(NameNode.java:564)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:584)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:762)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:746)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1438)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1504)
2015-10-25 11:29:55,204 INFO  util.ExitUtil - Exiting with status 1
2015-10-25 11:29:55,215 INFO  namenode.NameNode - SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down NameNode at lustre/10.20.10.126
************************************************************/
```

I've updated core-site.xml, mapred-site.xml and hdfs-site.xml .  My goal is to only install Hadoop on a single node of a 3-node LustreFS system.  Is this workflow supported?

**Comment by stephenskory** [comment]
Hi,

these two lines:

```
2015-10-25 11:29:54,426 INFO  namenode.NameNode - fs.defaultFS is lustrefs:///
2015-10-25 11:29:55,188 FATAL namenode.NameNode - Failed to start namenode.
```

tell me that HDFS (the NameNode) is configured to use Lustre, which is probably not what you want? What I think is going on is that you want HDFS to *not* use Lustre for its file system, while you want the other services to *do* use Lustre. I think you'll have to set the file system to HDFS or Lustre, correctly, in more than configuration file, such that HDFS doesn't use Lustre and the other services do. You may have to look carefully at the order in which each service parses the XML files.

Does that make sense?

**Comment by b-long** [comment]
Hi @stephenskory , thanks for responding.  I've worked past that issue with the Namenode's URI (it is using lustre, which for the time being I cannot change).  HDFS storage and MapReduce are working, however, I've noticed that simple MapReduce jobs (e.g. the [WordCount](https://github.com/apache/hadoop/blob/trunk/hadoop-mapreduce-project/hadoop-mapreduce-examples/src/main/java/org/apache/hadoop/examples/WordCount.java)) take a long time to complete.  It seems that a job can get to the RUNNING state in a reasonable amount of time, but from RUNNING to FINISHED can take a while.  In a recent test, I've had a job backed by Lustre take ~7 minutes to process [this example](https://github.com/apache/hadoop/blob/master/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/site/markdown/MapReduceTutorial.md#usage).  The same job, on identical nodes using vanilla HDFS finish in under a minute.  Any idea why that might be?

**Comment by stephenskory** [comment]
For some of the larger jobs we tried, we would see some similar things to this, but I can't say for sure it's the same issue. For us, playing with some of the Lustre settings helped, such as max_rpcs_in_flight, or some of the other common performance settings, or the file lock settings, did change our performance. Without an extensive dive into your system, I really can't say.

Good luck!

**Comment by b-long** [comment]
@stephenskory No worries, I appreciate the support :smile: I'll see if I can't come up with more reproducible steps and document this scenario (if it is in fact a bug).  Until then, closing this issue.  Thanks!
